// =============================================================================
// app/layout.tsx — Root Layout (Server Component)
// עוטף את כל הדפים: מגדיר פונטים, metadata, כיווניות RTL, ו-footer גלובלי.
// DEV NOTE: שנו את metadata.title/description לפרויקט שלכם.
// =============================================================================
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      dir="rtl"
    >
      <body className="min-h-full flex flex-col">{children}
        <footer className="w-full text-center p-3 text-xs text-gray-500 bg-white/80 border-t border-[#d8d1c8] mt-auto">
  <p>© {new Date().getFullYear()} פרויקט גמר. כל הזכויות שמורות.</p>
  <Link href="/privacy" className="hover:text-[#075E54] hover:underline mt-1 inline-block">
    מדיניות פרטיות ותנאי שימוש
  </Link>
</footer>
         </body>
    </html>
  );
}
